### ISSUE TITLE
error find john

### ISSUE THREAD

**Issue by feedb** [DanMcInerney/icebreaker#10]
Traceback (most recent call last):
  File "./icebreaker.py", line 1536, in <module>
    main(report, args)
  File "./icebreaker.py", line 1503, in main
    prev_creds, new_lines = parse_responder_log(args, prev_lines, prev_creds)
  File "./icebreaker.py", line 1092, in parse_responder_log
    prev_creds = get_cracked_pwds(prev_creds)
  File "./icebreaker.py", line 924, in get_cracked_pwds
    out, err = Popen('submodules/JohnTheRipper/run/john --show hashes/{}'.format(x).split(), stdout=PIPE, stderr=PIPE).communicate()
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'submodules/JohnTheRipper/run/john': 'submodules/JohnTheRipper/run/john'

**Comment by feedb** [comment]
fixed, john configuring with error
