### ISSUE TITLE
ModuleNotFoundError: No module named 'libtmux'

### ISSUE THREAD

**Issue by simonj-smith** [DanMcInerney/icebreaker#5]
Hi,
When I install and run "python3 icebreaker.py -l targets.txt" I get "ModuleNotFoundError: No module named 'libtmux'" . Anyone had experience of this and know what I'm doing wrong?
Thanks.

**Comment by DanMcInerney** [comment]
Did you run './setup.sh' then 'pipenv shell' before running the tool?
You're just missing the libtmux library which should be installed by the
./setup.sh command. My guess is you're running the tool outside the pipenv
environment or the 'pipenv install --three' command failed when you ran
./setup.sh.

**Comment by simonj-smith** [comment]
Hi Dan,
Thanks for the quick response, looks like it is 'pipenv install --three' that is having problems. Checking back I can see the below:

Running: pipenv install --three
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋usage: __main__.py [-h] [-p PYTHON] [-i PACKAGES] [-r REQUIREMENTS] [-d]
                   [-a PROJECT]
                   envname
__main__.py: error: too few arguments

Virtualenv location: 
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/local/lib/python2.7/site-packages/pipenv/cli.py", line 197, in install
    selective_upgrade=selective_upgrade
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/local/lib/python2.7/site-packages/pipenv/core.py", line 1731, in do_install
    ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy, skip_requirements=skip_requirements)
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/local/lib/python2.7/site-packages/pipenv/core.py", line 652, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/local/lib/python2.7/site-packages/pipenv/core.py", line 342, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/local/lib/python2.7/site-packages/pipenv/project.py", line 410, in create_pipfile
    config_parser = ConfigOptionParser(name=self.name)
  File "/root/.local/share/virtualenvs/icebreaker-2FivyZWy/local/lib/python2.7/site-packages/pipenv/patched/pip/baseparser.py", line 149, in __init__
    assert self.name
AssertionError
/root/.local/share/virtualenvs/icebreaker-2FivyZWy/local/lib/python2.7/site-packages/pipenv/utils.py:1147: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-CuZOA2-requirements'>
  warnings.warn(warn_message, ResourceWarning)
[*] Run "pipenv shell" before running icebreaker
[*] Example usage: ./icebreaker.py -l targets.txt

Previously I thought I was good after seeing the last 2 lines but it looks like something is causing a fail in that install. I tried an apt update and apt upgrade and total removal and re-clone of the git but still no joy. I am running in Kali Linux if that makes any difference.

**Comment by DanMcInerney** [comment]
I've been having a lot of weird issues with pipenv lately but that one is new. One way I solved my previous issue was to do 'pipenv install --two' then 'pipenv install --three' and it worked normally which is bizarre but worth a try.

**Comment by simonj-smith** [comment]
Did a clean install and followed your advice about doing the installs separately and manually and it's all working fine now.
Thanks for your help and a cool project.
